env:
  es2021: true
  node: true
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 12
  sourceType: module
rules:
  prettier/prettier: error
