env:
  es2021: true
  node: true
extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
